// The playground page bundles src/engine.mjs between the __ENGINE__ markers
// (regenerated by `npm run sync:playground`). If the bundle drifts from the
// real engine — an engine change that wasn't re-bundled — the demo would
// show verdicts the CLI would never produce. This test fails CI in that case.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  classify,
  classifyBranch,
  classifyRemote,
  globToRegExp,
  matchesAny,
} from "../src/classify.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "index.html"), "utf8");
const START = "/* __ENGINE_START__ */";
const END = "/* __ENGINE_END__ */";
const s = html.indexOf(START);
const e = html.indexOf(END);
assert.ok(
  s >= 0 && e > s,
  "index.html is missing the __ENGINE__ markers — run `npm run sync:playground`"
);

// Evaluate the bundled code in a fresh scope and pull out the engine surface.
// The bundle is plain top-level declarations (no `export`), so `new Function`
// can return them directly.
const bundledCode = html.slice(s + START.length, e);

// The fixture region holds the demo's pure data + shaping (no DOM). Eval it
// alongside the engine so the tests can run the page's exact pipeline.
const FS = "/* __FIXTURE_START__ */";
const FE = "/* __FIXTURE_END__ */";
const fs = html.indexOf(FS);
const fe = html.indexOf(FE);
assert.ok(
  fs >= 0 && fe > fs,
  "index.html is missing the __FIXTURE__ markers around makeRepo/shaping"
);
const fixtureCode = html.slice(fs + FS.length, fe);

const page = new Function(
  bundledCode +
    "\n" +
    fixtureCode +
    "\nreturn { globToRegExp, matchesAny, classify, classifyBranch, " +
    "classifyRemote, makeRepo, shapedBranch, demoConfig, RULES, " +
    "DEFAULT_THRESHOLDS };"
)();

function cfg(over = {}) {
  return {
    protected: [],
    deleteMergedAfterDays: 21,
    warnUnmergedAfterDays: 45,
    rules: [],
    pr: { track: true },
    remote: { pruneMerged: true, deleteAbandonedAfterDays: 0 },
    ...over,
  };
}

function ctx(over = {}) {
  return {
    isHead: false,
    baseNames: new Set(["origin/main", "main"]),
    baseShort: new Set(["main"]),
    ...over,
  };
}

function check(label, fn) {
  try {
    fn();
  } catch (err) {
    err.message = `${label}: ${err.message}`;
    throw err;
  }
}

test("page bundle vs engine: globToRegExp behaves identically", () => {
  const cases = [
    ["main", "main"], ["main", "main2"], ["feature/*", "feature/x"],
    ["feature/*", "feature/x/y"], ["feature/*", "feature/x-y"], ["feature/*", "other/x"],
    ["release/**", "release/v1"], ["release/**", "release/v1/hotfix"], ["release/**", "release"],
    ["**/feature", "feature"], ["**/feature", "a/b/feature"], ["**/feature", "featurex"],
    ["a/**/b", "a/b"], ["a/**/b", "a/x/y/b"], ["branch.one", "branchXone"],
    ["tmp-*", "tmp-old"], ["?", "x"], ["?", "xy"], ["[", "["], ["", ""], ["*", "a/b"],
  ];
  for (const [p, n] of cases) {
    check(`glob ${JSON.stringify(p)} vs ${JSON.stringify(n)}`, () => {
      assert.equal(page.globToRegExp(p).source, globToRegExp(p).source);
      assert.equal(page.globToRegExp(p).test(n), globToRegExp(p).test(n));
      assert.equal(page.matchesAny([p], n), matchesAny([p], n));
    });
  }
});

test("page bundle vs engine: classify agrees across the verdict space", () => {
  const branches = [
    // protected / head
    { name: "main", shortName: "main", type: "local", ageDays: 0, merged: true, isHead: true, pr: null },
    { name: "origin/release/v1", shortName: "release/v1", type: "remote", ageDays: 200, merged: true, pr: null },
    { name: "staging", shortName: "staging", type: "local", ageDays: 100, merged: false, pr: null },
    // integrated
    { name: "feature/merged-old", shortName: "feature/merged-old", type: "local", ageDays: 60, merged: true, pr: null },
    { name: "feature/merged-young", shortName: "feature/merged-young", type: "local", ageDays: 5, merged: true, pr: null },
    { name: "feature/squash-old", shortName: "feature/squash-old", type: "local", ageDays: 40, contentMerged: true, pr: null },
    { name: "feature/squash-young", shortName: "feature/squash-young", type: "local", ageDays: 3, contentMerged: true, pr: null },
    // unmerged + PR states
    { name: "feature/open-fresh", shortName: "feature/open-fresh", type: "local", ageDays: 20, pr: { state: "open", ageDays: 2 } },
    { name: "feature/open-stale", shortName: "feature/open-stale", type: "local", ageDays: 80, pr: { state: "open", ageDays: 40 } },
    { name: "wip/abandoned", shortName: "wip/abandoned", type: "local", ageDays: 120, pr: { state: "closed", ageDays: 100 } },
    { name: "docs/fresh", shortName: "docs/fresh", type: "local", ageDays: 6, pr: null },
    { name: "feature/stale", shortName: "feature/stale", type: "local", ageDays: 90, pr: null },
  ];
  const configs = [
    cfg(),
    cfg({ deleteMergedAfterDays: 0, warnUnmergedAfterDays: 0 }),
    cfg({ deleteMergedAfterDays: 90, warnUnmergedAfterDays: 200 }),
    cfg({ protected: ["vendor/**", "special/*"] }),
    cfg({ rules: [{ match: "tmp/*", mode: "any", minAgeDays: 1 }] }),
    cfg({ rules: [{ match: "feature/ci-*", mode: "merged", minAgeDays: 7 }] }),
    cfg({ rules: [{ match: "feature/*", mode: "merged", minAgeDays: 90 }] }),
    cfg({ rules: [{ match: "docs/**", mode: "merged" }] }),
  ];
  for (const c of configs) {
    for (const b of branches) {
      check(`classify(${b.name}, ${JSON.stringify(c)})`, () => {
        assert.deepEqual(page.classify(b, c, ctx()), classify(b, c, ctx()));
      });
    }
  }
  // Rule-driven cases (rules only apply to local branches).
  const ruled = [
    { name: "tmp/scratch", shortName: "tmp/scratch", type: "local", ageDays: 3, pr: null },
    { name: "tmp/scratch", shortName: "tmp/scratch", type: "local", ageDays: 0, pr: null },
    { name: "feature/ci-x", shortName: "feature/ci-x", type: "local", ageDays: 30, merged: true, pr: null },
    { name: "feature/ci-x", shortName: "feature/ci-x", type: "local", ageDays: 3, merged: true, pr: null },
    { name: "feature/ci-x", shortName: "feature/ci-x", type: "local", ageDays: 60, merged: false, pr: null },
    { name: "origin/tmp/scratch", shortName: "tmp/scratch", type: "remote", ageDays: 3, pr: null },
  ];
  for (const c of configs.slice(4)) {
    for (const b of ruled) {
      check(`classify(${b.name}, rules)`, () => {
        assert.deepEqual(page.classify(b, c, ctx()), classify(b, c, ctx()));
      });
    }
  }
});

// ---- page fixture vs the real analyze layering on the same inputs ---------

// Context analyze.mjs builds for the repo the fixture models: a remote origin
// whose default branch is main => baseRefs ["origin/main"], baseShort ["main"].
function analyzeCtx(branch) {
  return {
    isHead: branch.type === "remote" ? false : branch.isHead,
    baseNames: new Set(["origin/main"]),
    baseShort: new Set(["main"]),
  };
}

const SCENARIOS = [
  { label: "defaults", toggles: { squash: true, pr: true, remote: true }, thresholds: { merged: 21, warn: 45, aban: 0 } },
  { label: "content-merge off", toggles: { squash: false, pr: true, remote: true }, thresholds: { merged: 21, warn: 45, aban: 0 } },
  { label: "PR tracking off", toggles: { squash: true, pr: false, remote: true }, thresholds: { merged: 21, warn: 45, aban: 0 } },
  { label: "--remote off", toggles: { squash: true, pr: true, remote: false }, thresholds: { merged: 21, warn: 45, aban: 0 } },
  { label: "abandon after 60d", toggles: { squash: true, pr: true, remote: true }, thresholds: { merged: 21, warn: 45, aban: 60 } },
  { label: "everything young", toggles: { squash: true, pr: true, remote: true }, thresholds: { merged: 90, warn: 180, aban: 0 } },
];

function rowOutcomes(rows, toggles, thresholds) {
  const cfg = page.demoConfig(thresholds, toggles);
  return rows.map((b) => {
    const shaped = page.shapedBranch(b, toggles);
    const ctx = analyzeCtx(shaped);
    return {
      name: b.name,
      page: page.classifyBranch(shaped, cfg, ctx),
      real: classifyBranch(shaped, cfg, ctx),
    };
  });
}

test("page fixture rows agree with the real analyze layering on the same inputs", () => {
  const rows = page.makeRepo();
  assert.equal(rows.length, 13, "fixture should cover every branch role");

  for (const s of SCENARIOS) {
    for (const r of rowOutcomes(rows, s.toggles, s.thresholds)) {
      check(`fixture ${r.name} under ${s.label}`, () => {
        assert.deepEqual(r.page, r.real);
      });
    }
  }

  // The canonical default view the page shows on load (and reset). If the
  // engine or fixture ever changes the demo's story, this table must change
  // with it deliberately.
  const canonical = {
    main: ["keep", "head"],
    "release/v2": ["keep", "protected"],
    "origin/release/v1": ["keep", "protected"], // protected remotes are never pruned
    "feature/merged-old": ["delete", "merged"],
    "origin/feature/merged-old2": ["delete", "merged"],
    "feature/squash-landed": ["delete", "squash-merged"],
    "origin/feature/squash-landed": ["delete", "squash-merged"],
    "feature/slow-wip": ["keep", "unmerged-rule"],
    "wip/abandoned": ["warn", "stale-unmerged"],
    "origin/wip/abandoned": ["warn", "stale-unmerged"],
    "feature/open-pr": ["keep", "open-pr"],
    "tmp/scratch": ["delete", "rule-force"],
    "docs/fresh": ["keep", "active"],
  };
  const dflt = SCENARIOS[0];
  const counts = { delete: 0, warn: 0, keep: 0 };
  for (const r of rowOutcomes(rows, dflt.toggles, dflt.thresholds)) {
    assert.deepEqual([r.page.verdict, r.page.reason], canonical[r.name], r.name);
    counts[r.page.verdict]++;
  }
  assert.deepEqual(counts, { delete: 5, warn: 2, keep: 6 });

  // Toggle semantics the page must preserve (spot checks beyond equality).
  const byName = (out) => Object.fromEntries(out.map((r) => [r.name, r.page]));

  const off = byName(rowOutcomes(rows, SCENARIOS[3].toggles, SCENARIOS[3].thresholds));
  assert.deepEqual([off["origin/feature/merged-old2"].verdict, off["origin/feature/merged-old2"].reason], ["warn", "remote-disabled"]);
  assert.deepEqual([off["origin/release/v1"].verdict, off["origin/release/v1"].reason], ["keep", "protected"]);

  const noPr = byName(rowOutcomes(rows, SCENARIOS[2].toggles, SCENARIOS[2].thresholds));
  assert.equal(noPr["feature/open-pr"].reason, "active"); // PR state hidden => treated as unmerged

  const aban = byName(rowOutcomes(rows, SCENARIOS[4].toggles, SCENARIOS[4].thresholds));
  assert.deepEqual([aban["origin/wip/abandoned"].verdict, aban["origin/wip/abandoned"].reason], ["delete", "abandoned-pr"]);
  assert.equal(aban["wip/abandoned"].verdict, "warn", "abandoned local branches are only warned");

  const young = byName(rowOutcomes(rows, SCENARIOS[5].toggles, SCENARIOS[5].thresholds));
  assert.equal(young["feature/merged-old"].verdict, "keep");
  assert.equal(young["tmp/scratch"].verdict, "delete", "force rules ignore the age thresholds");
});

test("classifyBranch layer corners: protection wins, gate second, remote-disabled", () => {
  // Branches the fixture doesn't include but real repos produce — the places
  // where a naive "gate first" layering (or a mis-ordered one) would disagree
  // with analyze.mjs. Both the bundled page copy and the real engine must
  // answer identically and correctly.
  const togglesOn = { squash: true, pr: true, remote: true };
  const cfg = page.demoConfig({ merged: 21, warn: 45, aban: 0 }, togglesOn);
  const noGateCfg = page.demoConfig({ merged: 21, warn: 45, aban: 0 }, { squash: true, pr: true, remote: false });
  const abanCfg = page.demoConfig({ merged: 21, warn: 45, aban: 60 }, togglesOn);
  const cases = [
    // Protected remote, merged and old: keep — never pruned even with --remote.
    { name: "origin/release/v1", shortName: "release/v1", type: "remote", ageDays: 90, merged: true, pr: null, want: ["keep", "protected"], cfg },
    // Same branch younger than the merge threshold: still keep (protected).
    { name: "origin/release/v1", shortName: "release/v1", type: "remote", ageDays: 5, merged: true, pr: null, want: ["keep", "protected"], cfg },
    // Merged remote too young to delete: kept, not "remote-disabled".
    { name: "origin/feature/fresh", shortName: "feature/fresh", type: "remote", ageDays: 10, merged: true, pr: null, want: ["keep", "too-young"], cfg },
    // Old merged remote with --remote available: delete through the gate.
    { name: "origin/feature/old", shortName: "feature/old", type: "remote", ageDays: 60, merged: true, pr: null, want: ["delete", "merged"], cfg },
    // Remote default branch itself is never a candidate.
    { name: "origin/main", shortName: "main", type: "remote", ageDays: 200, merged: true, pr: null, want: ["keep", "protected"], cfg },
    // Abandoned remote PR past the threshold deletes via the gate, not a warn.
    { name: "origin/wip/ghost", shortName: "wip/ghost", type: "remote", ageDays: 120, pr: { state: "closed", ageDays: 90 }, want: ["delete", "abandoned-pr"], cfg: abanCfg },
    // Force rules never touch remote branches.
    { name: "origin/tmp/scratch", shortName: "tmp/scratch", type: "remote", ageDays: 3, pr: null, want: ["keep", "active"], cfg },
  ];
  for (const b of cases) {
    const ctx = analyzeCtx(b);
    check(`layer corner ${b.name}`, () => {
      const p = page.classifyBranch(b, b.cfg, ctx);
      const r = classifyBranch(b, b.cfg, ctx);
      assert.deepEqual(p, r);
      assert.deepEqual([p.verdict, p.reason], b.want);
    });
  }
  // --remote off: an old merged remote is informational only.
  const b = { name: "origin/feature/old", shortName: "feature/old", type: "remote", ageDays: 60, merged: true, pr: null };
  const ctx = analyzeCtx(b);
  for (const fn of [page.classifyBranch, classifyBranch]) {
    const d = fn(b, noGateCfg, ctx);
    assert.deepEqual([d.verdict, d.reason], ["warn", "remote-disabled"]);
  }
  // Local branches never see the remote gate (abandoned local = warn only).
  const loc = { name: "wip/ghost", type: "local", ageDays: 120, pr: { state: "closed", ageDays: 90 } };
  const lctx = { isHead: false, baseNames: new Set(["origin/main"]), baseShort: new Set(["main"]) };
  assert.equal(classifyBranch(loc, abanCfg, lctx).verdict, "warn");
  assert.equal(page.classifyBranch(loc, abanCfg, lctx).verdict, "warn");
});

test("page's test-count badge matches the suite", () => {
  // The page hardcodes its suite size in two places (header badge and the
  // "run it yourself" snippet). A stale claim is misleading feedback on the
  // demo surface, so pin it: count the actual tests and require the page to
  // agree. Update the page by editing those two numbers (or re-running sync).
  const dir = join(root, "test");
  let total = 0;
  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".test.mjs")) continue;
    const src = readFileSync(join(dir, name), "utf8");
    total += (src.match(/^\s*test\(/gm) || []).length;
  }
  assert.ok(total > 0, "expected to find test definitions in test/*.test.mjs");
  assert.match(
    html,
    new RegExp(`<b>${total}</b> tests`),
    `header badge must claim ${total} tests`
  );
  assert.match(
    html,
    new RegExp(`# ${total} unit \\+ integration tests`),
    `run-it-yourself snippet must claim ${total} tests`
  );
});

test("page bundle vs engine: classifyRemote agrees", () => {
  const branches = [
    { name: "origin/feature/a", shortName: "feature/a", type: "remote", ageDays: 50, merged: true, pr: null },
    { name: "origin/feature/b", shortName: "feature/b", type: "remote", ageDays: 10, merged: true, pr: null },
    { name: "origin/feature/c", shortName: "feature/c", type: "remote", ageDays: 50, contentMerged: true, pr: null },
    { name: "origin/wip/d", shortName: "wip/d", type: "remote", ageDays: 120, pr: { state: "closed", ageDays: 90 } },
    { name: "origin/wip/e", shortName: "wip/e", type: "remote", ageDays: 20, pr: { state: "closed", ageDays: 10 } },
    { name: "origin/wip/f", shortName: "wip/f", type: "remote", ageDays: 120, pr: { state: "open", ageDays: 90 } },
    { name: "origin/wip/g", shortName: "wip/g", type: "remote", ageDays: 120, pr: null },
  ];
  const configs = [
    cfg(),
    cfg({ remote: { pruneMerged: false, deleteAbandonedAfterDays: 0 } }),
    cfg({ remote: { pruneMerged: true, deleteAbandonedAfterDays: 60 } }),
    cfg({ deleteMergedAfterDays: 0, remote: { pruneMerged: true, deleteAbandonedAfterDays: 30 } }),
  ];  for (const c of configs) {
    for (const b of branches) {
      check(`classifyRemote(${b.name}, ${JSON.stringify(c.remote)})`, () => {
        assert.deepEqual(page.classifyRemote(b, c), classifyRemote(b, c));
      });
    }
  }
});

// ---- seeded property test ------------------------------------------------
// Hand-picked cases above can miss the combination that breaks parity. This
// throws hundreds of random branch x config x context shapes at BOTH the
// page's bundled engine and the real one and requires byte-identical
// verdicts. Deterministic: a fixed seed means a failure is reproducible.

function mulberry32(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const pick = (rnd, arr) => arr[Math.floor(rnd() * arr.length)];

const FUZZ_NAME_PARTS = [
  "feature/x",
  "feature/a-b",
  "feature/x/y",
  "feature/a_b.c",
  "docs/#ticket-7",
  "tmp/scratch",
  "tmp-1",
  "wip/abandoned",
  "wip/idea",
  "release/v1",
  "release/v1/hotfix",
  "hotfix/1.2.3",
  "bugfix/issue_9",
  "experiment/fancy-name",
  "JIRA-123",
  "feature/slow-wip",
  "main",
  "master",
  "dev",
  "develop",
  "staging",
  "qa",
  "trunk",
  "docs",
  "HEAD",
  "keep-local",
  "x",
];

const FUZZ_RULE_GLOBS = [
  "tmp/*",
  "tmp/**",
  "feature/*",
  "feature/**",
  "feature/slow-*",
  "wip/**",
  "release/**",
  "docs/*",
  "**/idea",
  "*.1",
  "JIRA-*",
  "experiment/**",
  "keep-*",
];

function randBranch(rnd, i) {
  const type = rnd() < 0.35 ? "remote" : "local";
  const short = pick(rnd, FUZZ_NAME_PARTS);
  const name = type === "remote" ? "origin/" + short : short;
  const r = rnd();
  const merged = r < 0.3;
  const contentMerged = r >= 0.3 && r < 0.5;
  const isHead =
    type === "local" &&
    (short === "main" || short === "master") &&
    rnd() < 0.6;
  return {
    name,
    // Mirror analyze.mjs: locals carry their own name as shortName; remotes
    // carry the name minus the remote prefix. Occasionally omit shortName
    // entirely to exercise the classify() fallback on both sides.
    ...(rnd() < 0.85 ? { shortName: type === "remote" ? short : name } : {}),
    type,
    ageDays: Math.floor(rnd() * 220),
    merged,
    contentMerged,
    isHead,
    pr:
      rnd() < 0.45
        ? {
            state: pick(rnd, ["open", "closed", "merged"]),
            ageDays: Math.floor(rnd() * 150),
            number: i,
          }
        : null,
  };
}

function randConfig(rnd) {
  const rules = [];
  if (rnd() < 0.55) {
    const n = 1 + Math.floor(rnd() * 3);
    for (let k = 0; k < n; k++) {
      const rule = {
        match: pick(rnd, FUZZ_RULE_GLOBS),
        mode: pick(rnd, ["merged", "any"]),
      };
      if (rnd() < 0.5) rule.minAgeDays = Math.floor(rnd() * 120);
      rules.push(rule);
    }
  }
  const protectedList = [];
  if (rnd() < 0.4) {
    protectedList.push(
      ...new Set([pick(rnd, FUZZ_NAME_PARTS), pick(rnd, FUZZ_RULE_GLOBS)])
    );
  }
  return {
    protected: protectedList,
    deleteMergedAfterDays: Math.floor(rnd() * 90),
    warnUnmergedAfterDays: Math.floor(rnd() * 200),
    rules,
    pr: { track: true },
    remote: {
      pruneMerged: rnd() < 0.7,
      deleteAbandonedAfterDays: rnd() < 0.5 ? 0 : Math.floor(rnd() * 200) + 1,
    },
  };
}

const BASE_REF_POOL = [
  ["origin/main"],
  ["origin/main", "origin/dev"],
  ["origin/main", "main"],
  ["main"],
  ["origin/main", "origin/develop", "release"],
];

function randCtx(rnd, branch) {
  const baseRefs = pick(rnd, BASE_REF_POOL);
  return {
    isHead: branch.type === "remote" ? false : branch.isHead,
    baseNames: new Set(baseRefs),
    baseShort: new Set(baseRefs.map((b) => b.split("/").pop())),
  };
}

test("fuzz: page bundle and engine agree on 2000 random branch x config x ctx shapes", () => {
  const rnd = mulberry32(0x6c7e2d);
  const verdicts = { delete: 0, warn: 0, keep: 0 };
  const reasons = new Set();
  let remotes = 0;
  let rulesSeen = 0;
  let protectedSeen = 0;

  for (let i = 0; i < 2000; i++) {
    const branch = randBranch(rnd, i);
    const cfg = randConfig(rnd);
    const ctx = randCtx(rnd, branch);
    if (branch.type === "remote") remotes++;
    if (cfg.rules.length > 0) rulesSeen++;

    check(`fuzz case ${i} (${branch.name}, merged=${branch.merged}, contentMerged=${branch.contentMerged}, age=${branch.ageDays}, rules=${cfg.rules.length})`, () => {
      // The full layering and each raw gate must agree byte-for-byte.
      const pb = page.classifyBranch(branch, cfg, ctx);
      assert.deepEqual(pb, classifyBranch(branch, cfg, ctx));
      assert.deepEqual(
        page.classify(branch, cfg, ctx),
        classify(branch, cfg, ctx)
      );
      assert.deepEqual(
        page.classifyRemote(branch, cfg),
        classifyRemote(branch, cfg)
      );

      // Structural sanity that must hold no matter the inputs.
      assert.ok(["delete", "warn", "keep"].includes(pb.verdict), pb.verdict);
      assert.ok(typeof pb.reason === "string" && pb.reason.length > 0);

      verdicts[pb.verdict]++;
      reasons.add(pb.reason);
      if (pb.reason === "protected" || pb.reason === "head") protectedSeen++;

      // Deterministic: classifying the same shape twice gives the same answer.
      assert.deepEqual(pb, page.classifyBranch(branch, cfg, ctx));

      // Glob behavior parity for the rules in play.
      for (const rule of cfg.rules) {
        assert.equal(
          page.globToRegExp(rule.match).source,
          globToRegExp(rule.match).source
        );
        assert.equal(
          page.matchesAny([rule.match], branch.shortName ?? branch.name),
          matchesAny([rule.match], branch.shortName ?? branch.name)
        );
      }
    });
  }

  // The generator must actually have exercised the space, or the test is
  // vacuously green: every verdict, a spread of reasons, remotes, rules,
  // and protected branches all seen.
  assert.ok(verdicts.delete > 50, `delete verdicts: ${verdicts.delete}`);
  assert.ok(verdicts.warn > 50, `warn verdicts: ${verdicts.warn}`);
  assert.ok(verdicts.keep > 100, `keep verdicts: ${verdicts.keep}`);
  assert.ok(reasons.size > 10, `reason variety: ${reasons.size}`);
  assert.ok(remotes > 200, `remote branches: ${remotes}`);
  assert.ok(rulesSeen > 400, `cases with rules: ${rulesSeen}`);
  assert.ok(protectedSeen > 50, `protected/head outcomes: ${protectedSeen}`);
});
