// The playground page bundles src/engine.mjs between the __ENGINE__ markers
// (regenerated by `npm run sync:playground`). If the bundle drifts from the
// real engine — an engine change that wasn't re-bundled — the demo would
// show verdicts the CLI would never produce. This test fails CI in that case.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  classify,
  classifyRemote,
  globToRegExp,
  matchesAny,
} from "../src/classify.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "index.html"), "utf8");
const START = "/* __ENGINE_START__ */";
const END = "/* __ENGINE_END__ */";
const s = html.indexOf(START);
const e = html.indexOf(END);
assert.ok(
  s >= 0 && e > s,
  "index.html is missing the __ENGINE__ markers — run `npm run sync:playground`"
);

// Evaluate the bundled code in a fresh scope and pull out the engine surface.
// The bundle is plain top-level declarations (no `export`), so `new Function`
// can return them directly.
const bundledCode = html.slice(s + START.length, e);
const page = new Function(
  bundledCode + "\nreturn { globToRegExp, matchesAny, classify, classifyRemote };"
)();

function cfg(over = {}) {
  return {
    protected: [],
    deleteMergedAfterDays: 21,
    warnUnmergedAfterDays: 45,
    rules: [],
    pr: { track: true },
    remote: { pruneMerged: true, deleteAbandonedAfterDays: 0 },
    ...over,
  };
}

function ctx(over = {}) {
  return {
    isHead: false,
    baseNames: new Set(["origin/main", "main"]),
    baseShort: new Set(["main"]),
    ...over,
  };
}

function check(label, fn) {
  try {
    fn();
  } catch (err) {
    err.message = `${label}: ${err.message}`;
    throw err;
  }
}

test("page bundle vs engine: globToRegExp behaves identically", () => {
  const cases = [
    ["main", "main"], ["main", "main2"], ["feature/*", "feature/x"],
    ["feature/*", "feature/x/y"], ["feature/*", "feature/x-y"], ["feature/*", "other/x"],
    ["release/**", "release/v1"], ["release/**", "release/v1/hotfix"], ["release/**", "release"],
    ["**/feature", "feature"], ["**/feature", "a/b/feature"], ["**/feature", "featurex"],
    ["a/**/b", "a/b"], ["a/**/b", "a/x/y/b"], ["branch.one", "branchXone"],
    ["tmp-*", "tmp-old"], ["?", "x"], ["?", "xy"], ["[", "["], ["", ""], ["*", "a/b"],
  ];
  for (const [p, n] of cases) {
    check(`glob ${JSON.stringify(p)} vs ${JSON.stringify(n)}`, () => {
      assert.equal(page.globToRegExp(p).source, globToRegExp(p).source);
      assert.equal(page.globToRegExp(p).test(n), globToRegExp(p).test(n));
      assert.equal(page.matchesAny([p], n), matchesAny([p], n));
    });
  }
});

test("page bundle vs engine: classify agrees across the verdict space", () => {
  const branches = [
    // protected / head
    { name: "main", shortName: "main", type: "local", ageDays: 0, merged: true, isHead: true, pr: null },
    { name: "origin/release/v1", shortName: "release/v1", type: "remote", ageDays: 200, merged: true, pr: null },
    { name: "staging", shortName: "staging", type: "local", ageDays: 100, merged: false, pr: null },
    // integrated
    { name: "feature/merged-old", shortName: "feature/merged-old", type: "local", ageDays: 60, merged: true, pr: null },
    { name: "feature/merged-young", shortName: "feature/merged-young", type: "local", ageDays: 5, merged: true, pr: null },
    { name: "feature/squash-old", shortName: "feature/squash-old", type: "local", ageDays: 40, contentMerged: true, pr: null },
    { name: "feature/squash-young", shortName: "feature/squash-young", type: "local", ageDays: 3, contentMerged: true, pr: null },
    // unmerged + PR states
    { name: "feature/open-fresh", shortName: "feature/open-fresh", type: "local", ageDays: 20, pr: { state: "open", ageDays: 2 } },
    { name: "feature/open-stale", shortName: "feature/open-stale", type: "local", ageDays: 80, pr: { state: "open", ageDays: 40 } },
    { name: "wip/abandoned", shortName: "wip/abandoned", type: "local", ageDays: 120, pr: { state: "closed", ageDays: 100 } },
    { name: "docs/fresh", shortName: "docs/fresh", type: "local", ageDays: 6, pr: null },
    { name: "feature/stale", shortName: "feature/stale", type: "local", ageDays: 90, pr: null },
  ];
  const configs = [
    cfg(),
    cfg({ deleteMergedAfterDays: 0, warnUnmergedAfterDays: 0 }),
    cfg({ deleteMergedAfterDays: 90, warnUnmergedAfterDays: 200 }),
    cfg({ protected: ["vendor/**", "special/*"] }),
    cfg({ rules: [{ match: "tmp/*", mode: "any", minAgeDays: 1 }] }),
    cfg({ rules: [{ match: "feature/ci-*", mode: "merged", minAgeDays: 7 }] }),
    cfg({ rules: [{ match: "feature/*", mode: "merged", minAgeDays: 90 }] }),
    cfg({ rules: [{ match: "docs/**", mode: "merged" }] }),
  ];
  for (const c of configs) {
    for (const b of branches) {
      check(`classify(${b.name}, ${JSON.stringify(c)})`, () => {
        assert.deepEqual(page.classify(b, c, ctx()), classify(b, c, ctx()));
      });
    }
  }
  // Rule-driven cases (rules only apply to local branches).
  const ruled = [
    { name: "tmp/scratch", shortName: "tmp/scratch", type: "local", ageDays: 3, pr: null },
    { name: "tmp/scratch", shortName: "tmp/scratch", type: "local", ageDays: 0, pr: null },
    { name: "feature/ci-x", shortName: "feature/ci-x", type: "local", ageDays: 30, merged: true, pr: null },
    { name: "feature/ci-x", shortName: "feature/ci-x", type: "local", ageDays: 3, merged: true, pr: null },
    { name: "feature/ci-x", shortName: "feature/ci-x", type: "local", ageDays: 60, merged: false, pr: null },
    { name: "origin/tmp/scratch", shortName: "tmp/scratch", type: "remote", ageDays: 3, pr: null },
  ];
  for (const c of configs.slice(4)) {
    for (const b of ruled) {
      check(`classify(${b.name}, rules)`, () => {
        assert.deepEqual(page.classify(b, c, ctx()), classify(b, c, ctx()));
      });
    }
  }
});

test("page's test-count badge matches the suite", () => {
  // The page hardcodes its suite size in two places (header badge and the
  // "run it yourself" snippet). A stale claim is misleading feedback on the
  // demo surface, so pin it: count the actual tests and require the page to
  // agree. Update the page by editing those two numbers (or re-running sync).
  const dir = join(root, "test");
  let total = 0;
  for (const name of readdirSync(dir)) {
    if (!name.endsWith(".test.mjs")) continue;
    const src = readFileSync(join(dir, name), "utf8");
    total += (src.match(/^\s*test\(/gm) || []).length;
  }
  assert.ok(total > 0, "expected to find test definitions in test/*.test.mjs");
  assert.match(
    html,
    new RegExp(`<b>${total}</b> tests`),
    `header badge must claim ${total} tests`
  );
  assert.match(
    html,
    new RegExp(`# ${total} unit \\+ integration tests`),
    `run-it-yourself snippet must claim ${total} tests`
  );
});

test("page bundle vs engine: classifyRemote agrees", () => {
  const branches = [
    { name: "origin/feature/a", shortName: "feature/a", type: "remote", ageDays: 50, merged: true, pr: null },
    { name: "origin/feature/b", shortName: "feature/b", type: "remote", ageDays: 10, merged: true, pr: null },
    { name: "origin/feature/c", shortName: "feature/c", type: "remote", ageDays: 50, contentMerged: true, pr: null },
    { name: "origin/wip/d", shortName: "wip/d", type: "remote", ageDays: 120, pr: { state: "closed", ageDays: 90 } },
    { name: "origin/wip/e", shortName: "wip/e", type: "remote", ageDays: 20, pr: { state: "closed", ageDays: 10 } },
    { name: "origin/wip/f", shortName: "wip/f", type: "remote", ageDays: 120, pr: { state: "open", ageDays: 90 } },
    { name: "origin/wip/g", shortName: "wip/g", type: "remote", ageDays: 120, pr: null },
  ];
  const configs = [
    cfg(),
    cfg({ remote: { pruneMerged: false, deleteAbandonedAfterDays: 0 } }),
    cfg({ remote: { pruneMerged: true, deleteAbandonedAfterDays: 60 } }),
    cfg({ deleteMergedAfterDays: 0, remote: { pruneMerged: true, deleteAbandonedAfterDays: 30 } }),
  ];
  for (const c of configs) {
    for (const b of branches) {
      check(`classifyRemote(${b.name}, ${JSON.stringify(c.remote)})`, () => {
        assert.deepEqual(page.classifyRemote(b, c), classifyRemote(b, c));
      });
    }
  }
});