# fish completion for git-cleanup
# Install:  git-cleanup completions fish > ~/.config/fish/completions/git-cleanup.fish

complete -c git-cleanup -n "__fish_use_subcommand" -a scan -d "Report branches that can be cleaned up (default)"
complete -c git-cleanup -n "__fish_use_subcommand" -a prune -d "Delete merged/stale branches (asks first)"
complete -c git-cleanup -n "__fish_use_subcommand" -a prs -d "List stale open pull requests"
complete -c git-cleanup -n "__fish_use_subcommand" -a report-issue -d "Keep one issue with a fixed title current on any forge"
complete -c git-cleanup -n "__fish_use_subcommand" -a doctor -d "Diagnose the environment (git, gh, tokens, config, remotes)"
complete -c git-cleanup -n "__fish_use_subcommand" -a backup -d "List backup bundles, or restore branches from one"
complete -c git-cleanup -n "__fish_seen_subcommand_from backup" -a list -d "List backup bundles"
complete -c git-cleanup -n "__fish_seen_subcommand_from backup" -a restore -d "Restore branches from a backup bundle"
complete -c git-cleanup -n "__fish_use_subcommand" -a completions -d "Print shell completions"
complete -c git-cleanup -n "__fish_use_subcommand" -a shell-hook -d "Print a shell or git hook snippet"
complete -c git-cleanup -n "__fish_use_subcommand" -a help -d "Show help"

complete -c git-cleanup -l yes -s y -d "Answer yes to every confirmation"
complete -c git-cleanup -l force -d "Alias for --yes"
complete -c git-cleanup -l remote -d "Also delete remote branches (git push --delete)"
complete -c git-cleanup -l repo -r -d "Analyze this repo (repeatable)"
complete -c git-cleanup -l config -r -d "Use this config file"
complete -c git-cleanup -l json -d "Machine-readable output"
complete -c git-cleanup -l summary -d "One line per repo: N prunable · M stale · K kept"
complete -c git-cleanup -l check -d "Exit code 2 when any branch is prunable"
complete -c git-cleanup -l verbose -s v -d "Show every branch"
complete -c git-cleanup -l no-pr -d "Do not query GitHub/GitLab for PR state"
complete -c git-cleanup -l close -d "(prs) Close stale open PRs"
complete -c git-cleanup -l title -r -d "(report-issue) Exact issue title to keep current"
complete -c git-cleanup -l dry-run -d "(report-issue) Rehearsal: search, no write"
complete -c git-cleanup -l version -s V -d "Print the version"
complete -c git-cleanup -l help -s h -d "Show help"